import React from "react";
import type { Metadata } from 'next'
import '../styles/globals.css'
import WithStoreProvider from "../processes/store-provider/WithStoreProvider";
import LayoutContainer from "../processes/layoutContainer/LayoutContainer";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body style={{marginRight: '0px !important'}}>
            <WithStoreProvider>
                <LayoutContainer>
                    {children}
                </LayoutContainer>
            </WithStoreProvider>
        </body>
    </html>
  )
}
